apiVersion: mysql.radondb.com/v1beta1
kind: Backup
metadata:
  name: backup-sample
spec:
  # Add fields here
  image: radondb/mysql57-sidecar:v3.0.0
  # hostfrom if empty, use the leader as hostfrom
  hostfrom: sample-mysql-0
  clusterName: sample
  # nfsServerAddress: ""
