apiVersion: v1
kind: Secret
metadata:
  # Corresponding to the user's secretName
  name: sample-user-password
data:
  # The key corresponding to the user's secretKey
  # Qing@123
  password: UWluZ0AxMjM=
  # A secret may store many passwords like this, so different keys are needed to distinguish
  # password2:
  # password3:
